package com.transion.eksath.blogic.dispatch.sagas.reviseDispatch;

public enum ReviseDispatchSagaState {
    REQUESTING_DISPATCH_UPDATE, AUTHORIZATION_INCREASED, COMPLETED, REQUESTING_AUTHORIZATION, REVERSING_DISPATCH_UPDATE, REVERSING_AUTHORIZATION, WAITING_FOR_CHANGE_TO_BE_MADE
}
