#Default port is 8761  all the files of this kind should be edited at the time of deployment

server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server: 
        waitTimeInMsWhenSyncEmpty: 5
    serviceUrl:
        defaultZone: http://localhost:8761