# 
# This is the core configuration for a configuration service. Two ways
#       
#       - A configuration service which completely loads the configuration for the services
#         from the local file service of the config service. This should be only be used for 
#         demonstration purposes or for a small application with limited number of services.
#       
#       - A configuration service that uses a git-based repository to read the files from 


#-------#

server:
    port : 8888
spring:
    cloud:
        config:
            server:
                encrypt.enabled: false
                git:
                    uri: https://github.com
                    searchPaths: dispath, feedback, profiles
                    username: native-cloud-apps
                    password: june

#-------#
# Classpath and file-based solution
#-------#

#server: 
#   port: 8888

#spring: 
#    profiles:
#        active:native
#    cloud:
#        config:
#            server:
#                native:
#                    searchLocations: 
